# Generated by Django 2.2.10 on 2020-02-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date',
            field=models.TextField(),
        ),
    ]
