# Generated by Django 2.2.10 on 2020-02-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testserver', '0005_auto_20200213_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
